version: "3.7"

services:
  weather_collector: &app
    build:
      dockerfile: Dockerfile
      context: .
    container_name: weather_collector
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=weather_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:11
    container_name: postgres_weather
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_data
    ports:
      - "5432:5432"

#  redis:
#    image: redis:alpine
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - "6379:6379"
